export const enum Psychotype {
  DEMONSTRATIVE_TYPE = 'DEMONSTRATIVE_TYPE',

  STUCK_TYPE = 'STUCK_TYPE',

  PEDANTIC_TYPE = 'PEDANTIC_TYPE',

  EXCITABLE_TYPE = 'EXCITABLE_TYPE',

  HYPERTHYMIC_TYPE = 'HYPERTHYMIC_TYPE',

  DYSTHYMIC_TYPE = 'DYSTHYMIC_TYPE',

  ANXIOUSLY_FEARFULL_TYPE = 'ANXIOUSLY_FEARFULL_TYPE',

  EMOTIONALLY_TYPE = 'EMOTIONALLY_TYPE',

  EMOTIVE_TYPE = 'EMOTIVE_TYPE',

  CYCLOTHYMIC_TYPE = 'CYCLOTHYMIC_TYPE',
}
